name: Simulate Status Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  simulate-check:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      statuses: write  # ✅ Needed to set status checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Simulated Status Check
        run: python .github/scripts/simulate_status_check.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
